---
name: "Feature request"
description: "Suggest an idea for this project / add a new BMS"
labels: "Feature+Request"
body:
- type: markdown
  attributes:
    value: Before you open a new feature request, search through the existing feature requests to see if others have had the same idea.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template to the best of my ability.
        required: true
      - label: I have understood that this integration is only about battery management systems with Bluetooth Low Energy support.
        required: true        
      - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
        required: true
      - label: This issue is not a duplicate feature request of [previous feature requests](https://github.com/patman15/BMS_BLE-HA/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).
        required: true

- type: textarea
  attributes:
    label: "Is your feature request related to a problem? Please describe."
    description: "A clear and concise description of what the problem is."
    placeholder: "I'm always frustrated when [...]"
  validations:
    required: true

- type: textarea
  attributes:
    label: "Describe the solution you'd like"
    description: "A clear and concise description of what you want to happen."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional context"
    description: "Add any other context (documentation) or screenshots about the feature request here."
    placeholder: "For new BMS, please provide any links to documentation, the BT protocol, emulators, other open source implementations, or the like."
  validations:
    required: false
