name: Validate with hassfest

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 6'  

jobs:
  validate-hassfest:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - name: HA validation
          uses: "home-assistant/actions/hassfest@master"
